-- 국내: USER_TBL, USER_VIEW, USER, MEMBER
-- 영어권: 복수형 USERS, MEMBERS

DROP TABLE USERS;
CREATE TABLE USERS (
	ID VARCHAR2(12) PRIMARY KEY,
	PASSWORD VARCHAR2(12) NOT NULL,
	NAME VARCHAR2(30) NOT NULL,
	ROLE VARCHAR2(6) NOT NULL
);
	
INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES('guest', 'guest123', '방문자', 'USER');

INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES('admin', 'admin123', '관리자', 'ASMIN');

INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES('member', 'member123', '일반회원', 'USER');

COMMIT

SELECT*FROM USERS;
SELECT COUNT(*) FROM USERS;

Class.forName("oracle.jdbc.OracleDriver");